/* 
 * Match API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines EventType
    /// </summary>
  //  [JsonConverter(typeof(StringEnumConverter))]
        public enum EventType
    {
        /// <summary>
        /// Enum GoalScored for value: GoalScored
        /// </summary>
        [EnumMember(Value = "GoalScored")]
        GoalScored = 1,
        /// <summary>
        /// Enum PenaltySuccess for value: PenaltySuccess
        /// </summary>
        [EnumMember(Value = "PenaltySuccess")]
        PenaltySuccess = 2,
        /// <summary>
        /// Enum PenaltyMiss for value: PenaltyMiss
        /// </summary>
        [EnumMember(Value = "PenaltyMiss")]
        PenaltyMiss = 3,
        /// <summary>
        /// Enum YellowCard for value: YellowCard
        /// </summary>
        [EnumMember(Value = "YellowCard")]
        YellowCard = 4,
        /// <summary>
        /// Enum RedCard for value: RedCard
        /// </summary>
        [EnumMember(Value = "RedCard")]
        RedCard = 5,
        /// <summary>
        /// Enum SubOn for value: SubOn
        /// </summary>
        [EnumMember(Value = "SubOn")]
        SubOn = 6,
        /// <summary>
        /// Enum SubOff for value: SubOff
        /// </summary>
        [EnumMember(Value = "SubOff")]
        SubOff = 7,
        /// <summary>
        /// Enum Assist for value: Assist
        /// </summary>
        [EnumMember(Value = "Assist")]
        Assist = 8    }
}
