/* 
 * Match API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// MatchEvent
    /// </summary>
    [DataContract]
        public partial class MatchEvent :  IEquatable<MatchEvent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatchEvent" /> class.
        /// </summary>
        /// <param name="type">type.</param>
        public MatchEvent(EventType type = default(EventType))
        {
            this.Type = type;
        }
        
        /// <summary>
        /// Gets or Sets Minute
        /// </summary>
        [DataMember(Name="minute", EmitDefaultValue=false)]
        public int? Minute { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public EventType Type { get; set; }

        /// <summary>
        /// Gets or Sets PlayerID
        /// </summary>
        [DataMember(Name="playerID", EmitDefaultValue=false)]
        public int? PlayerID { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MatchEvent {\n");
            sb.Append("  Minute: ").Append(Minute).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  PlayerID: ").Append(PlayerID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MatchEvent);
        }

        /// <summary>
        /// Returns true if MatchEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of MatchEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MatchEvent input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Minute == input.Minute ||
                    (this.Minute != null &&
                    this.Minute.Equals(input.Minute))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.PlayerID == input.PlayerID ||
                    (this.PlayerID != null &&
                    this.PlayerID.Equals(input.PlayerID))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Minute != null)
                    hashCode = hashCode * 59 + this.Minute.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.PlayerID != null)
                    hashCode = hashCode * 59 + this.PlayerID.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
