/* 
 * Match API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PlayerRequest
    /// </summary>
    [DataContract]
        public partial class PlayerRequest :  IEquatable<PlayerRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerRequest" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="dateOfBirth">dateOfBirth.</param>
        /// <param name="position">position.</param>
        /// <param name="activeInEvents">activeInEvents.</param>
        public PlayerRequest(string name = default(string), DateTime? dateOfBirth = default(DateTime?), string position = default(string), List<MatchEventRequest> activeInEvents = default(List<MatchEventRequest>))
        {
            this.Name = name;
            this.DateOfBirth = dateOfBirth;
            this.Position = position;
            this.ActiveInEvents = activeInEvents;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets DateOfBirth
        /// </summary>
        [DataMember(Name="dateOfBirth", EmitDefaultValue=false)]
        public DateTime? DateOfBirth { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name="position", EmitDefaultValue=false)]
        public string Position { get; set; }

        /// <summary>
        /// Gets or Sets ActiveInEvents
        /// </summary>
        [DataMember(Name="activeInEvents", EmitDefaultValue=false)]
        public List<MatchEventRequest> ActiveInEvents { get; set; }

        /// <summary>
        /// Gets or Sets NameHash
        /// </summary>
        [DataMember(Name="nameHash", EmitDefaultValue=false)]
        public int? NameHash { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlayerRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  DateOfBirth: ").Append(DateOfBirth).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  ActiveInEvents: ").Append(ActiveInEvents).Append("\n");
            sb.Append("  NameHash: ").Append(NameHash).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PlayerRequest);
        }

        /// <summary>
        /// Returns true if PlayerRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PlayerRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlayerRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.DateOfBirth == input.DateOfBirth ||
                    (this.DateOfBirth != null &&
                    this.DateOfBirth.Equals(input.DateOfBirth))
                ) && 
                (
                    this.Position == input.Position ||
                    (this.Position != null &&
                    this.Position.Equals(input.Position))
                ) && 
                (
                    this.ActiveInEvents == input.ActiveInEvents ||
                    this.ActiveInEvents != null &&
                    input.ActiveInEvents != null &&
                    this.ActiveInEvents.SequenceEqual(input.ActiveInEvents)
                ) && 
                (
                    this.NameHash == input.NameHash ||
                    (this.NameHash != null &&
                    this.NameHash.Equals(input.NameHash))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.DateOfBirth != null)
                    hashCode = hashCode * 59 + this.DateOfBirth.GetHashCode();
                if (this.Position != null)
                    hashCode = hashCode * 59 + this.Position.GetHashCode();
                if (this.ActiveInEvents != null)
                    hashCode = hashCode * 59 + this.ActiveInEvents.GetHashCode();
                if (this.NameHash != null)
                    hashCode = hashCode * 59 + this.NameHash.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
