version: '3'

services:
  sqlserver:
    image: fp_sql:latest
    networks:
      - fp_gateway
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sqlserver_P@ssword
    ports:
      - "1433:1433"
  apimock:
    image: fp_mockapi:latest
    ports:
      - "4992:4992"
  api:
    image: fp_api:latest
    networks:
      - fp_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports: 
      - "4991:4991"
    depends_on: 
      - sqlserver

networks:
  fp_gateway: {}
 

        
