/* 
 * Match API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MatchEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatchEventTests
    {
        // TODO uncomment below to declare an instance variable for MatchEvent
        //private MatchEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MatchEvent
            //instance = new MatchEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MatchEvent
        /// </summary>
        [Test]
        public void MatchEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatchEvent
            //Assert.IsInstanceOfType<MatchEvent> (instance, "variable 'instance' is a MatchEvent");
        }


        /// <summary>
        /// Test the property 'Minute'
        /// </summary>
        [Test]
        public void MinuteTest()
        {
            // TODO unit test for the property 'Minute'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'PlayerID'
        /// </summary>
        [Test]
        public void PlayerIDTest()
        {
            // TODO unit test for the property 'PlayerID'
        }

    }

}
