/* 
 * Match API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Match
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatchTests
    {
        // TODO uncomment below to declare an instance variable for Match
        //private Match instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Match
            //instance = new Match();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Match
        /// </summary>
        [Test]
        public void MatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Match
            //Assert.IsInstanceOfType<Match> (instance, "variable 'instance' is a Match");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Home'
        /// </summary>
        [Test]
        public void HomeTest()
        {
            // TODO unit test for the property 'Home'
        }
        /// <summary>
        /// Test the property 'Away'
        /// </summary>
        [Test]
        public void AwayTest()
        {
            // TODO unit test for the property 'Away'
        }
        /// <summary>
        /// Test the property 'Played'
        /// </summary>
        [Test]
        public void PlayedTest()
        {
            // TODO unit test for the property 'Played'
        }
        /// <summary>
        /// Test the property 'MatchEvents'
        /// </summary>
        [Test]
        public void MatchEventsTest()
        {
            // TODO unit test for the property 'MatchEvents'
        }

    }

}
