/* 
 * Match API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MatchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatchRequestTests
    {
        // TODO uncomment below to declare an instance variable for MatchRequest
        //private MatchRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MatchRequest
            //instance = new MatchRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MatchRequest
        /// </summary>
        [Test]
        public void MatchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatchRequest
            //Assert.IsInstanceOfType<MatchRequest> (instance, "variable 'instance' is a MatchRequest");
        }


        /// <summary>
        /// Test the property 'Played'
        /// </summary>
        [Test]
        public void PlayedTest()
        {
            // TODO unit test for the property 'Played'
        }
        /// <summary>
        /// Test the property 'Home'
        /// </summary>
        [Test]
        public void HomeTest()
        {
            // TODO unit test for the property 'Home'
        }
        /// <summary>
        /// Test the property 'Away'
        /// </summary>
        [Test]
        public void AwayTest()
        {
            // TODO unit test for the property 'Away'
        }

    }

}
