/* 
 * Match API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PlayerRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PlayerRequestTests
    {
        // TODO uncomment below to declare an instance variable for PlayerRequest
        //private PlayerRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlayerRequest
            //instance = new PlayerRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlayerRequest
        /// </summary>
        [Test]
        public void PlayerRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PlayerRequest
            //Assert.IsInstanceOfType<PlayerRequest> (instance, "variable 'instance' is a PlayerRequest");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Test]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'ActiveInEvents'
        /// </summary>
        [Test]
        public void ActiveInEventsTest()
        {
            // TODO unit test for the property 'ActiveInEvents'
        }
        /// <summary>
        /// Test the property 'NameHash'
        /// </summary>
        [Test]
        public void NameHashTest()
        {
            // TODO unit test for the property 'NameHash'
        }

    }

}
